export enum RequisitoAdicional {
  VIAJES = "VIAJES",
  HOSPEDAJE = "HOSPEDAJE",
  SER_TRANSPORTE =  "SER. TRANSPORTE",
  AMB_TERRESTRE = "AMB. TERRESTRE",
  AMB_AEREA = "AMB. AEREA",
  SILLA_RUEDAS = "SILLA RUEDAS",
  RECETA_MEDICA = "RECETA MEDICA"
}

